plugins {
    id 'com.android.application'
}

android {
    namespace 'org.teleagent.echopress'
    compileSdk 34

    defaultConfig {
        applicationId "org.teleagent.echopress"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {}
